### ISSUE TITLE
Packet numbering should start at 0 in each PN space

### ISSUE THREAD

**Issue by jlaine** [h2o/quicly#101]
First of all thanks so much for this QUIC implementation! I am currently trying to create a Python QUIC implementation and interop'ing it with quicly.

One thing I noticed is that quicly seems to use a single packet number counter for all the packets it sends. The draft 18 RFC says:

`Packet numbers in each space start at packet number 0.`

Am I mistaken in my interpretation?

**Comment by kazuho** [comment]
> First of all thanks so much for this QUIC implementation! I am currently trying to create a Python QUIC implementation and interop'ing it with quicly.

:+1:

The text permits is that a sender may use different packet number spaces for each packet type. However, because senders are allowed (or even encouraged) to have gaps in packet numbers, the requirement does not mandate the use of different packet number spaces. Therefore, we are using a unified number space for simplicity.

**Comment by jlaine** [comment]
Thanks for the clarification!
