### ISSUE TITLE
Assert consistency in future might be now

### ISSUE THREAD

**Issue by sknat** [h2o/quicly#234]
The following call to `assert_consistency` seems to fail in some cases 
https://github.com/h2o/quicly/blob/dd914302fa20a4762c41778f57addbfe7159f695/lib/quicly.c#L570

Calling `do_send` ends with a `update_loss_alarm` aka `quicly_loss_update_alarm` which ends with `if (r->alarm_at < now) r->alarm_at = now;` thus failing the assert.

**Comment by kazuho** [comment]
Thank you for reporting the issue and filing the PR.

Do you happen to know how to reproduce the issue (or how we end up in this situation)?

I ask this because the assertion is intentional. The intention behind the assertion is to check that we are making forward progress (without entering a busy loop, that repeatedly calls `quicly_send` without the timeout value being changed).

Below is the code that leads to the invocation of `assert_consistency`, and as you can see, we are trying to address the issue by calling `do_send` twice, when the first call does not set `alarm_at` to a time in the future.

```c
    /* emit packets */
    if ((ret = do_send(conn, &s)) != 0)
        return ret;
    /* We might see the timer going back to the past, if time-threshold loss timer fires first without being able to make any
     * progress (i.e. due to the payload of lost packet being cancelled), then PTO for the previously sent packet.  To accomodate
     * that, we allow to rerun the do_send function just once.
     */
    if (s.num_packets == 0 && conn->egress.loss.alarm_at <= now) {
        assert(conn->egress.loss.alarm_at == now);
        if ((ret = do_send(conn, &s)) != 0)
            return ret;
    }
    assert_consistency(conn, 1);
```

**Comment by sknat** [comment]
Hi Kazuho,

Thanks a lot for your reply. I did indeed push the PR button a bit quickly yesterday. In fact was following the issue I had in #233 
When trying to fix it I changed `quicly_send_stream` to allocate non ack_eliciting frames when len == 0 which ended up breaking this invariant (thus this lazy fix I can up with :D)

Investigating further, this situation was in fact linked to a race condition on our side that ended up messing with the scheduler, and marking streams as having data even though they didn't have any.

So I think I can close this one & thanks again for the pointer
