### ISSUE TITLE
2nd and later connections end up with `not found`

### ISSUE THREAD

**Issue by Winters123** [h2o/quicly#281]
Hi, 
I tried to run `quicly` client multiple times to retrieve a file from the server. But from 2nd round, the `client` just got the error of 'not found'. But I printed the file name out and it was actually there.
Any hint on how to solve that?

Cheers,

**Comment by bulbaasd24** [comment]
Hey, 
I tried the example-echo for multiple client, and it works fine.
Did you write the file to every buffer of a connection from the server side?

**Comment by Winters123** [comment]
Thanks for the reply. But I'm not sure if the `echo.c` and `cli.c` share the same logic. I printed out the error mesg from `send_file()` in `quicly.c`, it showed: `error opening file: too many open files`.

But it was just the 2nd file I was about to open. Weird..

**Comment by kazuho** [comment]
@Winters123 Has it been the case that the server is up for a certain amount of time, serving multiple requests?

If that is the case, you might have been hit by a bug that was only recently been resolved by #277. Previously, when a endpoint (in this case a server) closes a connection, there was a chance that the resources allocated for streams were not freed. This resource includes file descriptors.

**Comment by Winters123** [comment]
@kazuho I'm afraid this case is different (I'm on the latest branch). In my case, I kept the `server` running, and launched several `client` one after another (with 3sec sleep in between) to request different files from `server`. But it kept hitting `not found` (too many open files). 

From `run_client()`, what I can tell is that the client port is randomly specified, so I understand that the second connection may be totally different from the 1st.

**Comment by Winters123** [comment]
Could it be the case that during the 1st round of sending, there is buffer overflow encountered?

**Comment by kazuho** [comment]
@Winters123 Am I correct in assuming that you are seeing "too many open files" on the server-side, that ends up the server sending "not found"?

Assuming that is the case, this is a resource leak on the server side. And the only way to open excess number of file descriptors is by making system calls (e.g., `socket`, `open`), so it is likely that this issue is related to a buffer overflow.

In order to move forward, it might be a good idea to actually see what files are left open. You can check that by running `lsof -p <pid>` where <pid> is the process ID of the cli running as the server.

**Comment by Winters123** [comment]
Thanks for the prompt reply. The silly reason being that during the execution of first round, the code that I added long time (on the local repo) before caused the overflow. It's all my fault actually..

Sorry for the disturb and thanks again for the reply :)
