### ISSUE TITLE
echo example: Core Dumped

### ISSUE THREAD

**Issue by piano-man** [h2o/quicly#347]
When I run the echo server and send some stream data from my client, it simply crashes with this error:

**_examples-echo: /home/quicly/lib/quicly.c:3115: quicly_send_stream: Assertion `len != 0' failed.
Aborted (core dumped)_**.

This is what the stack trace of the dump looks like:

$0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
$1  0x00007f1e209d6801 in __GI_abort () at abort.c:79
$2  0x00007f1e209c639a in __assert_fail_base (
    fmt=0x7f1e20b4d7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x55ad2fc3ec54 "len != 0", 
    file=file@entry=0x55ad2fc3dc28 "/home/quicly/lib/quicly.c", 
    line=line@entry=3115, 
    function=function@entry=0x55ad2fc3f210 <__PRETTY_FUNCTION__.8714> "quicly_send_stream") at assert.c:92
$3  0x00007f1e209c6412 in __GI___assert_fail (
    assertion=assertion@entry=0x55ad2fc3ec54 "len != 0", 
    file=file@entry=0x55ad2fc3dc28 "/home/quicly/lib/quicly.c", 
    line=line@entry=3115, 
    function=function@entry=0x55ad2fc3f210 <__PRETTY_FUNCTION__.8714> "quicly_send_stream") at assert.c:101
$4  0x000055ad2fc34de8 in quicly_send_stream (
    stream=stream@entry=0x55ad30c99ef0, s=s@entry=0x7fffcbf43790)
    at /home/quicly/lib/quicly.c:3115
$5  0x000055ad2fc2b63b in default_stream_scheduler_do_send (
    self=<optimized out>, conn=0x55ad30c97ca0, s=0x7fffcbf43790)
    at /home/quicly/lib/defaults.c:303
$6  0x000055ad2fc3601b in do_send (s=0x7fffcbf43790, conn=0x55ad30c97ca0)
    at /home/quicly/lib/quicly.c:3909
$7  quicly_send (conn=0x55ad30c97ca0, dest=<optimized out>, 
    src=<optimized out>, datagrams=<optimized out>, 
    num_datagrams=<optimized out>, buf=<optimized out>, bufsize=14720)
    at /home/quicly/lib/quicly.c:3989
$8  0x000055ad2fc2a944 in run_loop (fd=3, client=0x0)
    at /home/quicly/examples/echo.c:254
$9  0x000055ad2fc189bf in main (argc=<optimized out>, argv=<optimized out>)
    at /home/quicly/examples/echo.c:398

**Comment by TheJokr** [comment]
I recently had the same issue when trying to get the echo example to work. You can fix it by adding ` && input.len > 0` to the if-condition [on line 141](../blob/master/examples/echo.c#L141). Another thing I had to fix was the call to quicly_connect  [on line 388](../blob/master/examples/echo.c#L388), where the pointers for destination and local address are switched up (destination address is NULL and local address is set to `sa` instead of the other way around).

After that it worked fine for me, but I didn't yet have time to open a PR.
