### ISSUE TITLE
Question: why the AES_128_CTR is used in header protection

### ISSUE THREAD

**Issue by mrpre** [h2o/quicly#91]
1. After generating initial secret, `setup_cipher` call `ptls_cipher_new` to init `AES_128_CTR` ctx.  
But  in [draft-18](https://www.ietf.org/id/draft-ietf-quic-tls-18.txt) I find `AES-ECB` should be used
```
5.4.3.  AES-Based Header Protection
...
mask = AES-ECB(hp_key, sample)
```  
 I want to know why ?

2. How `sample` is used in `AES-ECB` ? In my opinio, `sample` is used as input data which will be encrypted by hp_key under `AES-ECB` schedule. But I find `simple` is used as `iv` by call `ptls_cipher_init`. What's the role of `iv` under  `AES-CTR` schedule ?

**Comment by kazuho** [comment]
The outcome of using AES-CTR with IV being the sample is exactly the same as applying AES-ECB to the sample then XORing the content.

The reason we use CTR-based design is because it gives us agility between cipher suites (chacha20 is a stream cipher, meaning that it only has the CTR mode). In fact, IIRC agility is the primary reason we chose this particular design for PNE in the working group.

**Comment by mrpre** [comment]
Fair enough
